### PR TITLE
Main Loop updates featuring all kinds of input handling and other developer support.

### PR DESCRIPTION
**Pull request by heysweet**

### CODE REVIEW

**Comment by heysweet** [comment]
Can we merge in the updated mainloop?

**Comment by ixchow** [comment]
I didn't have time to merge it before the assignment went out, and am a bit
wary of changing things during the assignment period (don't want to break
people's collision tests). I am likely to merge into a new branch over the
weekend and then merge _that_ into master on Tuesday, though.

I will probably take the keycode handling intact, but change the mouse to
be more like the key handling (single mouse(position, buttonBits) function
- global variable for current mouse state).

I'll probably also install the mouse handlers for the whole window rather
than just the canvas. I realize this probably breaks multi-canvas games,
but I think that's a less common case, and Rainbow [
http://tchow.com/games/rainbow/play] taught me that people like to mouse
out of the game window.

Why is the mouseWheel delta clamped?

I will also merge the documentation, which I realize is sorely lacking for
mainloop at the moment.

**Comment by heysweet** [comment]
Actually don't merge, I'm working on fixing issues after realizing that nobody had time to test them. I'll let you know when things are fixed, and will look into the mouseWheel delta clamping...

**Comment by heysweet** [comment]
Also, I'll work on changing the mouse to be more similar to the keys, as you said you were going to do.

**Comment by heysweet** [comment]
Feel free to make whatever changes you said you'd wanted to make, though I believe I made all the changes you asked for.

**Comment by ixchow** [comment]
Taking this code (as the [mainloop-updates](https://github.com/ixchow/sald/tree/mainloop-updates) branch) with the following changes:
- SALD doesn't target IE < 9, so don't worry about the window.event object
- mouseButtons is now mouse.buttons
- keyCode and keyCodeToString no longer have external visibility
- keyString -> keyName ("keyString" strikes me as potentially referring to the string produced when pressing the key, analogous to keyChar)
- the key() function now takes a keyName instead of a keyCode. If we're doing this, we might as well do it all the way.
- I'm dubious on the keydown default prevention avoidance code, but leaving it in (might be confusing for developer who wants to use those keys)
- context menu suppression added to window instead of canvas, and removed useCapture parameter (takeRightClickInput might change after handler is installed)
- using 'window.addEventListener' to register all listeners instead of sometimes setting a property
- mouse events detected in window, not canvas
- event parameters renamed to uniform 'evt', instead of 'ev'
- json.hasOwnProperty() during the name-to-code mapping seems over-paranoid
- used similar code path for mouse button naming function, though this is perhaps overkill
- use https://developer.mozilla.org/en-US/docs/Web/Events/wheel instead of mousewheel (even though it breaks opera at the moment according to that page)
- single 'mouse' entrypoint for both motion and button events
- adjusted README.md to reflect changes
- "SPACEBAR" -> "SPACE" as per SDL and java conventions.

Remaining to resolve:
- it might be better to maintain a button state object rather than reading evt.buttons
- I'm in favor of removing the MVC reference from the README because I think it muddies more than it clarifies.
- the platform-agnostic name of the "windows" key is the "meta" key
- we should differentiate right and left SHIFT, CTRL, ALT, META -- if possible
- key() should probably have modifier state tracking

**Comment by heysweet** [comment]
How do you propose we do modifier state tracking? Currently a developer is capable of saying

key(keyName, isDown){
  if (isDown && keyName == "C" && "CONTROL" in sald.keys){
    doCopy();
  }
}

I agree it feels sort of sloppy, but curious if you foresee a better way to support it.

**Comment by heysweet** [comment]
"I'm dubious on the keydown default prevention avoidance code, but leaving it in (might be confusing for developer who wants to use those keys)" 

I'm of the opinion that being clear on it's a keyDown and a keyUp (i.e. there should be one of each) is more clear, any developer that want to have something happen every frame of the update can perform a 

("SPACE" in sald.keys) on each clock tick, instead of every time the operating system decided it was appropriate to fire a key press, giving OS independent control over that aspect as well.

**Comment by heysweet** [comment]
Also not sure if ideal way for developers to compare keypresses is via

if ("SPACE" in sald.keys)

or

if (sald.keyName.SPACE in sald.keys)

The former seems to imply documentation of each key's name that the developer would have to be aware of, whereas the latter gives IDE's the opportunity to interject and let the developer know what keyName they may be looking for.

**Comment by ixchow** [comment]
Re: keydown default prevention -- I'm actually referring to the [code](https://github.com/ixchow/sald/blob/mainloop-updates/sald/mainloop.js#L240-245) that explicitly doesn't track "CONTROL" or "WINDOWS"

Interesting point on the key names. Didn't think of it because I don't use syntax-completing IDEs. That's a reasonable argument for exposing "sald.keyNames" and "sald.buttonNames" or similar (sald.constants.keyNames ?).

**Comment by heysweet** [comment]
Oh I see... well I choose those specifically to allow for META-TAB (on mac, windows equivalent to ALT-TAB) and other functions that I expected SHOULD work while others shouldn't? It was entirely arbitrary, but brings a bigger question:

Which keybindings should SALD not interrupt, which should SALD automatically interrupt (spacebar and arrow keys being an obvious subset of the answer), and which should SALD maybe allow the user to override (bringing to question right clicking, and the merits of allowing right click on a page that would embed the game in a canvas, but not pop a context menu up in the game itself)?

That was the reason I didn't allow right clicking outside of the canvas, but mouse movement was fine. It was an arbitrary decision I made, but a logical one. Seems like these questions need to be answered more formally built toward developer expectations and uses for SALD (do you embed SALD on a website, or is a given URL meant to only support a SALD game?).

**Comment by ixchow** [comment]
SALD is meant to be a framework for ludum dare games packaged as a single html file. I think this strongly implies that the game is the extent of the content on the page. As such, I'm okay with capturing as many events as possible, as way of giving the developer a very simple model ("if the user presses a key or mouse button, you handle it, not the web browser").

In my experience as a developer of this sort of game, I find the browser's default behaviors either inconsequential or annoying.

**Comment by heysweet** [comment]
I don't disagree, though when I tried to META-TAB and my computer wouldn't do it, it felt like an unexpected behavior.

**Comment by heysweet** [comment]
And would imagine the same for META-Q (quit), META-H (hide), and other behaviors that I associate with the operating system rather than the browser.

**Comment by ixchow** [comment]
I would argue that allowing the web page to handle these events is a bug (or at least misguided feature) in the web browser, and not our problem to work around.

**Comment by heysweet** [comment]
Fair enough. I defer to your decision.

**Comment by heysweet** [comment]
Though I imagine Chrome (the browser I'm using) made those decisions to allow a difference between, say, a fullscreen mode and regular, expected, tabbed behaviors.

**Pull request closed without merging**
